-- ========================================================
-- 1. RECENTLY ADDED DESTINATIONS (Jaisalmer, Pondicherry, Maldives, Tokyo & Kyoto, Paris)
-- ========================================================
INSERT INTO public.destinations (
  id, name, state, country, region, category, image, gallery, rating, reviews_count, discount_percent, starting_price, original_price, description, long_description, best_season, climate, coordinates, tags, popular_attractions
) VALUES 
(
  'dest-jaisalmer',
  'Jaisalmer & Thar Desert',
  'Rajasthan',
  'India',
  'North-West India',
  'heritage',
  'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?auto=format&fit=crop&w=800&q=80',
  ARRAY['https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?auto=format&fit=crop&w=1200&q=80', 'https://images.unsplash.com/photo-1477587458883-47145ed94245?auto=format&fit=crop&w=1200&q=80', 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80'],
  4.94,
  1950,
  20,
  12999,
  16250,
  'The Golden City of yellow sandstone fortresses, rolling Thar dunes, starlit camel safaris, and royal Havelis.',
  'Rising like a mirage from the Thar Desert, Jaisalmer mesmerizes with its 800-year-old living Golden Fort, intricately carved Patwon Ki Haveli, sunset camel caravans on Sam Sand Dunes, and nocturnal desert music under starlit skies.',
  'Oct – Mar',
  'Desert Continental, 12°C to 27°C in winter',
  '{"lat":26.9157,"lng":70.9083}'::jsonb,
  ARRAY['Golden Fort', 'Thar Desert', 'Camel Safari', 'Swiss Tents', 'Kalbelia Folk Dance'],
  ARRAY['Jaisalmer Golden Fort (Sonar Qila)', 'Sam Sand Dunes', 'Patwon Ki Haveli', 'Gadisar Lake']
),
(
  'dest-pondicherry',
  'Pondicherry & Auroville',
  'Puducherry',
  'India',
  'Coromandel Coast',
  'beach',
  'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=800&q=80',
  ARRAY['https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=1200&q=80', 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80'],
  4.89,
  2420,
  22,
  9499,
  12199,
  'French Riviera of the East with mustard-yellow colonial villas, Promenade coastal walks, and spiritual Auroville.',
  'Pondicherry blends French elegance with Indian coastal warmth. Cycle through the tree-lined boulevards of White Town, savor artisanal French croissants, meditate at the golden Matrimandir in Auroville, and enjoy sunset strolls on Rock Beach Promenade.',
  'Oct – Mar',
  'Tropical Maritime, 22°C to 31°C',
  '{"lat":11.9416,"lng":79.8083}'::jsonb,
  ARRAY['French Colony', 'Promenade Beach', 'Auroville Matrimandir', 'Cafes', 'Surfing'],
  ARRAY['Rock Beach Promenade', 'Auroville Golden Matrimandir', 'French Quarter (White Town)', 'Paradise Beach']
),
(
  'dest-maldives',
  'Maldives (Baa & South Ari)',
  'Baa Atoll',
  'Maldives',
  'Indian Ocean',
  'international',
  'https://images.unsplash.com/photo-1514282401047-d79a71a590e8?auto=format&fit=crop&w=800&q=80',
  ARRAY['https://images.unsplash.com/photo-1514282401047-d79a71a590e8?auto=format&fit=crop&w=1200&q=80', 'https://images.unsplash.com/photo-1573843981267-be1999ff37cd?auto=format&fit=crop&w=1200&q=80'],
  4.98,
  16800,
  30,
  48999,
  69999,
  'Tropical paradise of luxury overwater bungalows, neon turquoise lagoons, vibrant coral reefs, and manta ray safaris.',
  'The undisputed sovereign of island luxury. Glide above crystal-clear azure waters in private seaplanes, stay in iconic overwater villas with ocean-slide decks, dine in underwater restaurants, and snorkel alongside gentle whale sharks and manta rays in UNESCO Biosphere Baa Atoll.',
  'Nov – Apr',
  'Tropical Oceanic, 26°C to 31°C year-round',
  '{"lat":3.2028,"lng":73.2207}'::jsonb,
  ARRAY['Overwater Villa', 'Coral Reefs', 'Manta Rays', 'Underwater Dining', 'Seaplane'],
  ARRAY['Hanifaru Bay Manta Sanctuary', 'Ari Atoll Coral Lagoons', 'Male Grand Mosque', 'Bioluminescent Beach']
),
(
  'dest-tokyo',
  'Tokyo & Kyoto (Japan)',
  'Honshu',
  'Japan',
  'East Asia',
  'international',
  'https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&w=800&q=80',
  ARRAY['https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&w=1200&q=80', 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=1200&q=80'],
  4.96,
  19400,
  20,
  64999,
  81250,
  'Harmonious fusion of neon futurism in Shibuya, sacred Shinto shrines in Kyoto, bullet trains, and Mount Fuji.',
  'Japan invites you on an unforgettable journey from the ultra-modern skyline and cutting-edge robotics of Tokyo to the thousand vermilion torii gates of Fushimi Inari and peaceful bamboo groves of Arashiyama in Kyoto, all linked by 320 km/h Shinkansen bullet trains.',
  'Mar – May (Cherry Blossoms) & Sep – Nov (Autumn Foliage)',
  'Temperate Maritime, 12°C to 24°C',
  '{"lat":35.6762,"lng":139.6503}'::jsonb,
  ARRAY['Mount Fuji', 'Shinkansen Bullet Train', 'Cherry Blossoms', 'Shibuya Crossing', 'Kyoto Temples'],
  ARRAY['Mount Fuji 5th Station & Lake Kawaguchi', 'Fushimi Inari-Taisha Kyoto', 'Shibuya Scramble Crossing', 'Arashiyama Bamboo Forest']
),
(
  'dest-paris',
  'Paris & French Riviera',
  'Île-de-France & Provence',
  'France',
  'Western Europe',
  'international',
  'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=800&q=80',
  ARRAY['https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=1200&q=80', 'https://images.unsplash.com/photo-1509299349698-dd22323b5963?auto=format&fit=crop&w=1200&q=80'],
  4.94,
  22100,
  25,
  69999,
  93300,
  'City of Lights with Eiffel Tower sunsets, Louvre art masterpieces, Seine river cruises, and sunny Côte d’Azur glamour.',
  'Experience the world’s most romantic destination. Sip espresso in Montmartre sidewalk cafes, gaze out from the summit of the Eiffel Tower, admire Da Vinci’s Mona Lisa at the Louvre, and take the TGV high-speed train to Nice and Monaco along the Mediterranean coast.',
  'Apr – Oct',
  'Temperate Oceanic, 15°C to 26°C',
  '{"lat":48.8566,"lng":2.3522}'::jsonb,
  ARRAY['Eiffel Tower', 'Louvre Museum', 'Seine River Cruise', 'French Riviera', 'Gourmet Pastries'],
  ARRAY['Eiffel Tower Summit', 'The Louvre Museum', 'Palace of Versailles', 'Nice Promenade des Anglais']
)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  state = EXCLUDED.state,
  country = EXCLUDED.country,
  region = EXCLUDED.region,
  category = EXCLUDED.category,
  image = EXCLUDED.image,
  gallery = EXCLUDED.gallery,
  rating = EXCLUDED.rating,
  reviews_count = EXCLUDED.reviews_count,
  discount_percent = EXCLUDED.discount_percent,
  starting_price = EXCLUDED.starting_price,
  original_price = EXCLUDED.original_price,
  description = EXCLUDED.description,
  long_description = EXCLUDED.long_description,
  best_season = EXCLUDED.best_season,
  climate = EXCLUDED.climate,
  coordinates = EXCLUDED.coordinates,
  tags = EXCLUDED.tags,
  popular_attractions = EXCLUDED.popular_attractions;

-- ========================================================
-- 2. RECENTLY ADDED TOUR PACKAGES (Jaisalmer, Andaman, Maldives, Japan, Singapore, Vietnam)
-- ========================================================
INSERT INTO public.packages (
  id, title, destination, state, country, duration, days_count, nights_count, original_price, discounted_price, badge, image, rating, reviews_count, highlights, includes_flight, category, itinerary, inclusions, exclusions
) VALUES 
(
  'pkg-jaisalmer',
  'Jaisalmer Royal Desert Safari & Thar Glamping',
  'Jaisalmer, Sam Sand Dunes & Thar Desert',
  'Rajasthan',
  'India',
  '4 Days / 3 Nights',
  4,
  3,
  17499,
  12999,
  'Hot Deal',
  'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?auto=format&fit=crop&w=800&q=80',
  4.93,
  420,
  ARRAY['Luxury Swiss Tent with Private Bath on Sam Dunes', 'Sunset Camel Caravan & 4x4 Jeep Dune Bashing', 'Living Golden Sandstone Fort Guided Walk', 'Kalbelia Folk Dance & Rajasthani Gatte Ki Sabzi Dinner'],
  false,
  'heritage',
  '[]'::jsonb,
  ARRAY['1 Night in Boutique Haveli in Jaisalmer Old City', '2 Nights in Luxury Swiss Desert Tents on Sam Dunes', 'Buffet Breakfast & Traditional Royal Rajasthani Dinners', 'Sunset Camel Safari & Thar Jeep Dune Bashing', 'Evening Bonfire with Live Manganiyar Music & Folk Dance'],
  ARRAY['Airfare to Jodhpur / Jaisalmer', 'Monument camera fees']
),
(
  'pkg-andaman',
  'Andaman Coral Islands & Radhanagar Scuba Odyssey',
  'Port Blair, Havelock & Neil Island',
  'Andaman & Nicobar',
  'India',
  '6 Days / 5 Nights',
  6,
  5,
  38999,
  29499,
  'Best Seller',
  'https://images.unsplash.com/photo-1589308078059-be1415eab4c3?auto=format&fit=crop&w=800&q=80',
  4.95,
  890,
  ARRAY['Radhanagar Beach (Asia’s Best Beach Sunset)', 'Makruzz Premium High-Speed Island Ferry', 'Elephant Beach Snorkeling & Coral Viewing', 'Historic Cellular Jail Light & Sound Show'],
  true,
  'beach',
  '[]'::jsonb,
  ARRAY['Roundtrip Flights from Chennai / Kolkata / Delhi', '5 Nights in Beachfront 4★/5★ Resorts', 'All Inter-Island transfers via AC High-Speed Cruise (Makruzz/Green Ocean)', 'Complimentary Discover Scuba / Snorkeling Session with Instructor', 'Daily Breakfast buffet & private AC road transfers'],
  ARRAY['Deep Sea Scuba Certification courses', 'Personal water sports not specified']
),
(
  'pkg-maldives',
  'Maldives Luxury Overwater Villa & Coral Lagoon Retreat',
  'Baa Atoll & South Ari Atoll',
  'Baa Atoll',
  'Maldives',
  '5 Days / 4 Nights',
  5,
  4,
  79999,
  56999,
  'Ultra Luxury',
  'https://images.unsplash.com/photo-1514282401047-d79a71a590e8?auto=format&fit=crop&w=800&q=80',
  4.99,
  1120,
  ARRAY['Private Overwater Lagoon Villa with Glass-Floor & Sunken Deck', 'Scenic Twin Otter Seaplane Flights Over Coral Atolls', 'Guided Snorkeling with Gentle Whale Sharks & Manta Rays', 'Sunset Dolphin Watching Cruise with Champagne'],
  true,
  'beach',
  '[]'::jsonb,
  ARRAY['Roundtrip Flights to Male International Airport', 'Roundtrip Scenic Seaplane Airport Transfers', '4 Nights in 5★ Deluxe Overwater Lagoon Villa', 'All-Inclusive Meal Plan (Breakfast, Lunch, Multi-Course Dinner & Drinks)', 'Complimentary Snorkeling Equipment & Non-Motorized Water Sports'],
  ARRAY['Motorized watercraft rentals (Jet Ski)', 'Spa wellness therapies']
),
(
  'pkg-japan',
  'Japan Golden Blossom: Tokyo, Mt. Fuji & Kyoto',
  'Tokyo, Hakone (Mt. Fuji) & Kyoto',
  'Honshu',
  'Japan',
  '7 Days / 6 Nights',
  7,
  6,
  94999,
  74999,
  'Best Seller',
  'https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&w=800&q=80',
  4.96,
  640,
  ARRAY['320 km/h Shinkansen Bullet Train Experience', 'Mount Fuji 5th Station & Lake Ashi Pirate Ship Cruise', 'Kyoto Fushimi Inari 10,000 Torii Gates & Arashiyama Bamboo Grove', 'Shibuya Sky 360° Glass Observation Deck'],
  true,
  'heritage',
  '[]'::jsonb,
  ARRAY['Roundtrip International Flights to Tokyo Narita/Haneda', '6 Nights in Premium 4★/5★ City Hotels & Onsen Ryokan', '7-Day JR Shinkansen Bullet Train Rail Pass', 'All Sightseeing Excursions with English-Speaking Chaperone', 'Daily Japanese & Western Buffet Breakfast'],
  ARRAY['Japan Tourist Visa fees', 'Lunches & dinners not mentioned']
),
(
  'pkg-singapore',
  'Singapore Futuristic Marvel & Sentosa Island',
  'Marina Bay, Sentosa Island & Mandai',
  'Central Region',
  'Singapore',
  '5 Days / 4 Nights',
  5,
  4,
  42999,
  32999,
  'Hot Deal',
  'https://images.unsplash.com/photo-1525625293386-3f8f99389edd?auto=format&fit=crop&w=800&q=80',
  4.91,
  810,
  ARRAY['Universal Studios Singapore VIP Access', 'Gardens by the Bay Supertree Grove & Cloud Forest Waterfall', 'Marina Bay Sands SkyPark Observation Deck', 'Night Safari Tram Ride Through Rainforest'],
  true,
  'international',
  '[]'::jsonb,
  ARRAY['Roundtrip Flights to Singapore Changi Airport', '4 Nights in 4★ Central Downtown Hotel', 'Universal Studios Singapore Full-Day Ticket', 'Gardens by the Bay Flower Dome & Cloud Forest passes', 'Daily Breakfast buffet & private airport transfers'],
  ARRAY['Singapore Tourist Visa', 'Personal shopping & meals']
),
(
  'pkg-vietnam',
  'Vietnam Golden Hand Bridge & Ha Long Bay Cruise',
  'Hanoi, Ha Long Bay & Da Nang',
  'Quang Ninh & Da Nang',
  'Vietnam',
  '6 Days / 5 Nights',
  6,
  5,
  44999,
  34999,
  'New Offer',
  'https://images.unsplash.com/photo-1528127269322-539801943592?auto=format&fit=crop&w=800&q=80',
  4.94,
  530,
  ARRAY['5★ Luxury Overnight Cruise in Ha Long Bay with Balcony Cabin', 'Ba Na Hills Sun World & Famous Golden Hand Bridge', 'Hoi An UNESCO Lantern Riverboat Ride', 'Hanoi French Quarter & Water Puppet Show'],
  true,
  'international',
  '[]'::jsonb,
  ARRAY['Roundtrip Flights to Hanoi & Da Nang', '1 Night on 5★ Ha Long Bay Luxury Cruise (All Meals on Board)', '4 Nights in 4★/5★ Boutique City & Beach Hotels', 'Ba Na Hills Cable Car & Golden Bridge VIP ticket', 'Daily Breakfast & Private Guided Excursions'],
  ARRAY['Vietnam E-Visa fees', 'Beverages on cruise']
)
ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  destination = EXCLUDED.destination,
  original_price = EXCLUDED.original_price,
  discounted_price = EXCLUDED.discounted_price,
  image = EXCLUDED.image,
  highlights = EXCLUDED.highlights,
  inclusions = EXCLUDED.inclusions,
  exclusions = EXCLUDED.exclusions;

-- ========================================================
-- 3. RECENTLY ADDED HOTELS & RESORTS (Suryagarh Jaisalmer, Palais de Mahe, Gili Lankanfushi Maldives, Hoshinoya Kyoto, The Leela Palace Delhi, Taj Exotica Havelock)
-- ========================================================
INSERT INTO public.hotels (
  id, name, location, city, state, country, image, price_per_night, original_price, rating, reviews_count, stars, type, amenities, coordinates, rooms_available, description, room_types
) VALUES 
(
  'hotel-suryagarh-jaisalmer',
  'Suryagarh Jaisalmer',
  'Kahala Phata, Sam Road',
  'Jaisalmer',
  'Rajasthan',
  'India',
  'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?auto=format&fit=crop&w=800&q=80',
  21999,
  28000,
  4.97,
  1240,
  5,
  'heritage_palace',
  ARRAY['Neel Sunken Heated Pool', 'Rait Desert Spa', 'Thar Camel Safari', 'Bageecha Organic Dining', 'Halwai Breakfast'],
  '{"lat":26.9157,"lng":70.9083}'::jsonb,
  5,
  'A palatial golden sandstone fortress rooted in Thar Desert lore. Offers royal sun-drenched courtyards, peacock gardens, desert musical soirees, and bespoke desert dinners.',
  '[{"name":"Fort Room","pricePerNight":21999,"capacity":"2 Adults","bedType":"1 King Bed","amenities":["Handcrafted Stone Jharokha","Courtyard View","Royal Bath Amenities"]},{"name":"Suryagarh Suite","pricePerNight":36000,"capacity":"3 Adults","bedType":"1 King Bed + Living Lounge","amenities":["Private Terrace","Thar Desert Panorama","Butler Service"]}]'::jsonb
),
(
  'hotel-palais-pondicherry',
  'Palais de Mahe - CGH Earth',
  'Bussy Street, White Town',
  'Puducherry',
  'Puducherry',
  'India',
  'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=800&q=80',
  14500,
  19000,
  4.92,
  880,
  5,
  'boutique_hotel',
  ARRAY['Courtyard Swimming Pool', 'Les Alizes French Seafood Bistro', 'Ayurvedic Wellness Spa', 'Heritage Bicycle Tours'],
  '{"lat":11.9333,"lng":79.8333}'::jsonb,
  4,
  'Immaculately styled French colonial mansion featuring arched verandahs, period teakwood furnishings, high ceilings, and a serene central courtyard pool.',
  '[{"name":"Deluxe Heritage Room","pricePerNight":14500,"capacity":"2 Adults","bedType":"1 Four-Poster King Bed","amenities":["Courtyard Pool View","Period Teak Decor","Walk-in Rain Shower"]}]'::jsonb
),
(
  'hotel-soneva-maldives',
  'Gili Lankanfushi Luxury Overwater Sanctuary',
  'Lankanfushi Island, North Male Atoll',
  'North Male Atoll',
  'Kaafu Atoll',
  'Maldives',
  'https://images.unsplash.com/photo-1514282401047-d79a71a590e8?auto=format&fit=crop&w=800&q=80',
  68000,
  88000,
  4.99,
  2420,
  5,
  'resort',
  ARRAY['Overwater Ocean Hammocks', 'Mr./Ms. Friday Private Butler', 'Meera Overwater Spa', 'Open-Air Jungle Cinema', 'Underground Wine Cellar'],
  '{"lat":4.2952,"lng":73.5583}'::jsonb,
  3,
  'Eco-luxury island sanctuary celebrated as one of the world’s top resorts. Overwater villas crafted from sustainable teak feature open-air rooftop sun decks and catamaran net hammocks over turquoise lagoons.',
  '[{"name":"Villa Suite with Private Water Garden","pricePerNight":68000,"capacity":"2 Adults, 1 Child","bedType":"1 King Bed","amenities":["Direct Lagoon Lagoon Step Access","Rooftop Sun Deck","Overwater Net Hammock","Dedicated Butler"]}]'::jsonb
),
(
  'hotel-leela-delhi',
  'The Leela Palace New Delhi',
  'Diplomatic Enclave, Chanakyapuri',
  'New Delhi',
  'Delhi',
  'India',
  'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=80',
  24500,
  32000,
  4.95,
  2680,
  5,
  'heritage_palace',
  ARRAY['Temperature-Controlled Rooftop Infinity Pool', 'Le Cirque French Restaurant', 'MEGU Japanese Dining', 'ESPA Royal Spa'],
  '{"lat":28.5828,"lng":77.1895}'::jsonb,
  7,
  'Architectural masterpiece combining the majesty of Lutyens’ Delhi with royal North Indian palace architecture. Houses museum-quality Indian art and a heated rooftop infinity pool.',
  '[{"name":"Grande Deluxe Palace Room","pricePerNight":24500,"capacity":"2 Adults","bedType":"1 King Bed","amenities":["Murano Glass Chandeliers","Pevonia Spa Bath Products","Walk-in Wardrobe"]}]'::jsonb
),
(
  'hotel-taj-andaman',
  'Taj Exotica Resort & Spa Havelock',
  'Radhanagar Beach No. 7, Havelock Island',
  'Havelock Island',
  'Andaman & Nicobar',
  'India',
  'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=800&q=80',
  32000,
  41000,
  4.96,
  1420,
  5,
  'resort',
  ARRAY['Olympic-Length Infinity Pool', 'Canopy Rainforest Walkway', 'PADI Certified Scuba Desk', 'Jiva Ayurvedic Spa', 'Shoreline Seafood Dining'],
  '{"lat":11.9761,"lng":92.9876}'::jsonb,
  4,
  '46-acre sanctuary bordered by coconut groves and tropical canopy on Havelock Island. Sustainable villas constructed with plantation timber, footsteps away from the white sands of Radhanagar Beach.',
  '[{"name":"Andaman Luxury Villa","pricePerNight":32000,"capacity":"2 Adults, 1 Child","bedType":"1 King Bed","amenities":["Rainforest Deck","Deep Soaking Tub","Complimentary Snorkel Gear"]}]'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  location = EXCLUDED.location,
  city = EXCLUDED.city,
  state = EXCLUDED.state,
  country = EXCLUDED.country,
  price_per_night = EXCLUDED.price_per_night,
  original_price = EXCLUDED.original_price,
  rooms_available = EXCLUDED.rooms_available,
  image = EXCLUDED.image,
  description = EXCLUDED.description,
  room_types = EXCLUDED.room_types;
